### ISSUE TITLE
Allow reusing PyMouseEvent instance multiple times.

### ISSUE THREAD

**Issue by qria** [SavinaRoja/PyUserInput#89] opened 2016-06-17 05:47 UTC
Currently if you run an instance of `PyMouseEvent` after it is stopped once, it will immediately stop itself because `self.state` is set to `False`.

I wanted to reuse some of my `PyMouseEvent` classes so I simply added `self.state=True` in `self.run()`.

I see no reason for this to not be a default behavior.

Here is a simple usecase/code for this.

```python
from pymouse import PyMouseEvent

class OnetimeClickListener(PyMouseEvent):
    """ Waits for a user to click and save the position """
    def run(self):
        self.state = True
        super(OnetimeClickListener, self).run()
    def click(self, x, y, button, press):
        if not press:
            # Ignore Mouse Up events
            return
        self.position = (x, y)
        self.stop()

# Example code

listener = OnetimeClickListener()

print("Please click to set position1")
listener.run()
pos1 = listener.position

print("Please click to set position2")
listener.run()
pos2 = listener.position

print("Please click to set position3")
listener.run()
pos3 = listener.position

```

**Comment by pepijndevos** [comment] 2016-06-17 05:56
Note that the project has moved to an organisation.I think that the issue is that some implementations use threads to listen to events, and as far as I know threads can not be restarted. I'll verify this later.                                                                                                                                                                                  ‎

**Comment by qria** [comment] 2016-06-17 07:07
Oh should I repost there? Or maybe wait for you to verify it?

**Comment by pepijndevos** [comment] 2016-07-16 09:17
See? https://github.com/PyUserInput/PyUserInput/blob/master/pymouse/base.py#L107
So definitely a wontfix.

**Closed by pepijndevos** 2016-07-16 09:17 UTC
